# coding: utf-8

# flake8: noqa

"""
    Fitness Tracking App API

    A simple REST API for tracking workout sessions

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "APIInfoApi",
    "HealthApi",
    "RootApi",
    "WorkoutsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HTTPValidationError",
    "LocationInner",
    "ValidationError",
    "WorkoutCreate",
    "WorkoutResponse",
]

# import apis into sdk package
from openapi_client.api.api_info_api import APIInfoApi as APIInfoApi
from openapi_client.api.health_api import HealthApi as HealthApi
from openapi_client.api.root_api import RootApi as RootApi
from openapi_client.api.workouts_api import WorkoutsApi as WorkoutsApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from openapi_client.models.location_inner import LocationInner as LocationInner
from openapi_client.models.validation_error import ValidationError as ValidationError
from openapi_client.models.workout_create import WorkoutCreate as WorkoutCreate
from openapi_client.models.workout_response import WorkoutResponse as WorkoutResponse

