# coding: utf-8

"""
    Fitness Tracking App API

    A simple REST API for tracking workout sessions

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkoutCreate(BaseModel):
    """
    Schema for creating a new workout.  Calories are automatically calculated based on activity type and duration.  Calorie Calculation Rules:     - running: duration * 10 calories/min     - cycling: duration * 8 calories/min     - walking: duration * 5 calories/min     - others: duration * 6 calories/min  Validation Rules:     - user_name must not be empty (1-100 characters)     - activity must not be empty (1-100 characters)     - duration must be a positive integer (> 0)
    """ # noqa: E501
    user_name: Annotated[str, Field(min_length=1, strict=True, max_length=100)] = Field(description="Name of the user")
    activity: Annotated[str, Field(min_length=1, strict=True, max_length=100)] = Field(description="Type of activity")
    duration: Annotated[int, Field(strict=True, gt=0)] = Field(description="Duration in minutes (must be > 0)")
    __properties: ClassVar[List[str]] = ["user_name", "activity", "duration"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkoutCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkoutCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_name": obj.get("user_name"),
            "activity": obj.get("activity"),
            "duration": obj.get("duration")
        })
        return _obj


