# coding: utf-8

"""
    Fitness Tracking App API

    A simple REST API for tracking workout sessions

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkoutResponse(BaseModel):
    """
    Schema for workout API responses.  Extends WorkoutBase with database fields. Used for serializing Workout model instances in API responses.  Attributes:     id: Unique workout identifier
    """ # noqa: E501
    user_name: Annotated[str, Field(min_length=1, strict=True, max_length=100)] = Field(description="Name of the user")
    activity: Annotated[str, Field(min_length=1, strict=True, max_length=100)] = Field(description="Type of activity")
    duration: Annotated[int, Field(strict=True, gt=0)] = Field(description="Duration in minutes (must be > 0)")
    calories: Annotated[int, Field(strict=True, gt=0)] = Field(description="Calories burned (must be > 0)")
    id: StrictInt = Field(description="Unique workout identifier")
    __properties: ClassVar[List[str]] = ["user_name", "activity", "duration", "calories", "id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkoutResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkoutResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_name": obj.get("user_name"),
            "activity": obj.get("activity"),
            "duration": obj.get("duration"),
            "calories": obj.get("calories"),
            "id": obj.get("id")
        })
        return _obj


